import { ACPFieldMetadata } from './acp-product';

/**
 * Complete ACP field definitions
 * Used for validation, UI generation, and documentation
 */
export const ACP_FIELDS: ACPFieldMetadata[] = [
  // Core Required Fields
  {
    name: 'id',
    label: 'Product ID',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Unique product identifier - max 100 characters',
    example: 'SKU-12345',
  },
  {
    name: 'title',
    label: 'Title',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Product title - max 150 characters',
    example: 'Wireless Bluetooth Headphones',
  },
  {
    name: 'description',
    label: 'Description',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Full product description in plain text only - max 5,000 characters',
    example: 'Premium wireless headphones with active noise cancellation...',
  },
  {
    name: 'link',
    label: 'Product URL',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Product detail page URL - must resolve with HTTP 200',
    example: 'https://example.com/products/wireless-headphones',
  },
  {
    name: 'price',
    label: 'Price',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Product price with ISO 4217 currency code',
    example: '99.99 USD',
  },
  {
    name: 'availability',
    label: 'Availability',
    required: true,
    type: 'enum',
    category: 'core',
    description: 'Current product availability status',
    example: 'in_stock',
    enumValues: ['in_stock', 'out_of_stock', 'preorder'],
  },
  {
    name: 'enable_search',
    label: 'Enable Search',
    required: true,
    type: 'boolean',
    category: 'core',
    description: 'Controls whether product can be surfaced in ChatGPT search',
    example: 'true',
  },
  {
    name: 'enable_checkout',
    label: 'Enable Checkout',
    required: true,
    type: 'boolean',
    category: 'core',
    description: 'Allows direct purchase through ChatGPT (requires enable_search=true)',
    example: 'true',
  },
  {
    name: 'inventory_quantity',
    label: 'Inventory Quantity',
    required: true,
    type: 'number',
    category: 'core',
    description: 'Actual stock quantity available - non-negative integer',
    example: '150',
  },
  {
    name: 'product_category',
    label: 'Product Category',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Product category taxonomy using ">" separator',
    example: 'Electronics > Audio > Headphones',
  },
  {
    name: 'material',
    label: 'Material',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Primary material composition - max 100 characters',
    example: 'Plastic, Metal, Foam',
  },
  {
    name: 'weight',
    label: 'Weight',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Product weight with unit (kg, lbs, g, oz)',
    example: '0.25 kg',
  },
  {
    name: 'image_link',
    label: 'Image URL',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Main product image URL (JPEG or PNG)',
    example: 'https://example.com/images/product.jpg',
  },
  {
    name: 'seller_name',
    label: 'Seller Name',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Seller or merchant display name - max 70 characters',
    example: 'Premium Electronics Store',
  },
  {
    name: 'seller_url',
    label: 'Seller URL',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Seller/merchant website URL',
    example: 'https://example.com',
  },
  {
    name: 'return_policy',
    label: 'Return Policy URL',
    required: true,
    type: 'string',
    category: 'core',
    description: 'Link to complete returns policy',
    example: 'https://example.com/returns',
  },
  {
    name: 'return_window',
    label: 'Return Window (days)',
    required: true,
    type: 'number',
    category: 'core',
    description: 'Number of days allowed for returns - positive integer',
    example: '30',
  },

  // Recommended Fields
  {
    name: 'gtin',
    label: 'GTIN',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Global Trade Item Number (UPC, EAN, JAN, ISBN) - 8-14 digits',
    example: '00123456789012',
  },
  {
    name: 'mpn',
    label: 'MPN',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Manufacturer Part Number (required if no GTIN) - max 70 characters',
    example: 'WH-1000XM4',
  },
  {
    name: 'brand',
    label: 'Brand',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Brand or manufacturer name - max 70 characters',
    example: 'Sony',
  },
  {
    name: 'condition',
    label: 'Condition',
    required: false,
    type: 'enum',
    category: 'recommended',
    description: 'Product condition (required if not new)',
    example: 'new',
    enumValues: ['new', 'refurbished', 'used'],
  },
  {
    name: 'popularity_score',
    label: 'Popularity Score',
    required: false,
    type: 'number',
    category: 'recommended',
    description: 'Product popularity score (0-5 scale or merchant-defined) for ranking',
    example: '4.5',
  },
  {
    name: 'return_rate',
    label: 'Return Rate',
    required: false,
    type: 'number',
    category: 'recommended',
    description: 'Product return rate percentage (0-100) for quality signals',
    example: '2.5',
  },
  {
    name: 'seller_privacy_policy',
    label: 'Privacy Policy URL',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Privacy policy URL (required if checkout enabled)',
    example: 'https://example.com/privacy',
  },
  {
    name: 'seller_tos',
    label: 'Terms of Service URL',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Terms of service URL (required if checkout enabled)',
    example: 'https://example.com/terms',
  },
  {
    name: 'product_review_count',
    label: 'Product Review Count',
    required: false,
    type: 'number',
    category: 'recommended',
    description: 'Total number of product reviews',
    example: '245',
  },
  {
    name: 'product_review_rating',
    label: 'Product Review Rating',
    required: false,
    type: 'number',
    category: 'recommended',
    description: 'Average product rating (0-5 scale)',
    example: '4.7',
  },
  {
    name: 'q_and_a',
    label: 'Q&A',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Product Q&A content in plain text',
    example: 'Q: Is it waterproof? A: Yes, IP67 rated.',
  },
  {
    name: 'raw_review_data',
    label: 'Reviews',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Full customer review text (plain text or JSON)',
    example: 'Great product! Very comfortable...',
  },
  {
    name: 'related_product_id',
    label: 'Related Products',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Related product IDs (comma-separated)',
    example: 'SKU-12346,SKU-12347',
  },
  {
    name: 'relationship_type',
    label: 'Relationship Type',
    required: false,
    type: 'enum',
    category: 'recommended',
    description: 'Type of relationship with related products',
    example: 'often_bought_with',
    enumValues: [
      'part_of_set',
      'required_part',
      'often_bought_with',
      'substitute',
      'different_brand',
      'accessory',
    ],
  },
  {
    name: 'geo_price',
    label: 'Geographic Price',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Region-specific pricing (e.g., "US:99.99 USD,CA:129.99 CAD")',
    example: 'US:99.99 USD,UK:89.99 GBP',
  },
  {
    name: 'geo_availability',
    label: 'Geographic Availability',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Region-specific availability (e.g., "US:in_stock,CA:out_of_stock")',
    example: 'US:in_stock,UK:out_of_stock',
  },
  {
    name: 'warning',
    label: 'Warning',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Regulatory disclaimers or product warnings',
    example: 'California Prop 65 Warning...',
  },
  {
    name: 'warning_url',
    label: 'Warning URL',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'URL to detailed warning information',
    example: 'https://example.com/warnings/prop65',
  },
  {
    name: 'age_restriction',
    label: 'Age Restriction',
    required: false,
    type: 'number',
    category: 'recommended',
    description: 'Minimum age required to purchase',
    example: '18',
  },
  {
    name: 'google_product_category',
    label: 'Google Product Category',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Google product category taxonomy',
    example: 'Electronics > Audio > Headphones',
  },
  {
    name: 'product_type',
    label: 'Product Type',
    required: false,
    type: 'string',
    category: 'recommended',
    description: 'Custom product categorization',
    example: 'Audio Equipment > Over-Ear Headphones',
  },

  // Optional Fields
  {
    name: 'additional_image_link',
    label: 'Additional Images',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Additional product image URLs (comma-separated)',
    example: 'https://example.com/img2.jpg,https://example.com/img3.jpg',
  },
  {
    name: 'video_link',
    label: 'Video URL',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Publicly accessible product video URL',
    example: 'https://example.com/videos/product-demo.mp4',
  },
  {
    name: 'model_3d_link',
    label: '3D Model URL',
    required: false,
    type: 'string',
    category: 'optional',
    description: '3D model file URL (GLB/GLTF format)',
    example: 'https://example.com/models/product.glb',
  },
  {
    name: 'color',
    label: 'Color',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product color - max 40 characters',
    example: 'Midnight Black',
  },
  {
    name: 'size',
    label: 'Size',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product size - max 20 characters',
    example: 'Large',
  },
  {
    name: 'dimensions',
    label: 'Dimensions',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product dimensions in LxWxH format',
    example: '20x18x8 cm',
  },
  {
    name: 'length',
    label: 'Length',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product length (use with width and height)',
    example: '20 cm',
  },
  {
    name: 'width',
    label: 'Width',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product width (use with length and height)',
    example: '18 cm',
  },
  {
    name: 'height',
    label: 'Height',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product height (use with length and width)',
    example: '8 cm',
  },
  {
    name: 'pattern',
    label: 'Pattern',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product pattern',
    example: 'Solid',
  },
  {
    name: 'age_group',
    label: 'Age Group',
    required: false,
    type: 'enum',
    category: 'optional',
    description: 'Target age group',
    example: 'adult',
    enumValues: ['newborn', 'infant', 'toddler', 'kids', 'adult'],
  },
  {
    name: 'gender',
    label: 'Gender',
    required: false,
    type: 'enum',
    category: 'optional',
    description: 'Target gender',
    example: 'unisex',
    enumValues: ['male', 'female', 'unisex'],
  },
  {
    name: 'sale_price',
    label: 'Sale Price',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Sale price with currency (must be ≤ regular price)',
    example: '79.99 USD',
  },
  {
    name: 'sale_price_effective_date',
    label: 'Sale Price Dates',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Sale price effective date range (ISO 8601)',
    example: '2025-01-01T00:00:00Z/2025-01-31T23:59:59Z',
  },
  {
    name: 'unit_pricing_measure',
    label: 'Unit Pricing Measure',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product quantity for unit pricing (use with base_measure)',
    example: '750 ml',
  },
  {
    name: 'base_measure',
    label: 'Base Measure',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Base unit for price comparison (use with unit_pricing_measure)',
    example: '100 ml',
  },
  {
    name: 'pricing_trend',
    label: 'Pricing Trend',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Historical price trend indicator - max 80 characters',
    example: 'Lowest price in 6 months',
  },
  {
    name: 'availability_date',
    label: 'Availability Date',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Date when preorder product will be available (ISO 8601)',
    example: '2025-03-15T00:00:00Z',
  },
  {
    name: 'expiration_date',
    label: 'Expiration Date',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Date to remove product from catalog (ISO 8601)',
    example: '2025-12-31T23:59:59Z',
  },
  {
    name: 'pickup_method',
    label: 'Pickup Method',
    required: false,
    type: 'enum',
    category: 'optional',
    description: 'In-store pickup availability',
    example: 'in_store',
    enumValues: ['in_store', 'reserve', 'not_supported'],
  },
  {
    name: 'pickup_sla',
    label: 'Pickup SLA',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Pickup service level agreement (e.g., "2 hours")',
    example: '2 hours',
  },
  {
    name: 'item_group_id',
    label: 'Item Group ID',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Variant group identifier - max 70 characters',
    example: 'headphones-wireless-2024',
  },
  {
    name: 'item_group_title',
    label: 'Item Group Title',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Parent product title for variant group - max 150 characters',
    example: 'Wireless Headphones',
  },
  {
    name: 'size_system',
    label: 'Size System',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Size system standard (ISO 3166 country code)',
    example: 'US',
  },
  {
    name: 'offer_id',
    label: 'Offer ID',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Unique offer identifier (SKU + seller + price)',
    example: 'SKU-12345-seller123-99.99',
  },
  {
    name: 'custom_variant1_category',
    label: 'Custom Variant 1 Category',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom variant dimension category',
    example: 'Material',
  },
  {
    name: 'custom_variant1_option',
    label: 'Custom Variant 1 Option',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom variant dimension value',
    example: 'Leather',
  },
  {
    name: 'custom_variant2_category',
    label: 'Custom Variant 2 Category',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Second custom variant dimension category',
    example: 'Finish',
  },
  {
    name: 'custom_variant2_option',
    label: 'Custom Variant 2 Option',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Second custom variant dimension value',
    example: 'Matte',
  },
  {
    name: 'custom_variant3_category',
    label: 'Custom Variant 3 Category',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Third custom variant dimension category',
    example: 'Edition',
  },
  {
    name: 'custom_variant3_option',
    label: 'Custom Variant 3 Option',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Third custom variant dimension value',
    example: 'Limited',
  },
  {
    name: 'shipping',
    label: 'Shipping',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Shipping options and costs (format: "country:region:service:price")',
    example: 'US:CA:Standard:5.99 USD',
  },
  {
    name: 'delivery_estimate',
    label: 'Delivery Estimate',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Estimated delivery date (ISO 8601)',
    example: '2025-02-15T00:00:00Z',
  },
  {
    name: 'store_review_count',
    label: 'Store Review Count',
    required: false,
    type: 'number',
    category: 'optional',
    description: 'Total number of store/brand reviews',
    example: '1542',
  },
  {
    name: 'store_review_rating',
    label: 'Store Review Rating',
    required: false,
    type: 'number',
    category: 'optional',
    description: 'Average store/brand rating (0-5 scale)',
    example: '4.3',
  },
  {
    name: 'custom_label_0',
    label: 'Custom Label 0',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom label for categorization',
  },
  {
    name: 'custom_label_1',
    label: 'Custom Label 1',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom label for categorization',
  },
  {
    name: 'custom_label_2',
    label: 'Custom Label 2',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom label for categorization',
  },
  {
    name: 'custom_label_3',
    label: 'Custom Label 3',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom label for categorization',
  },
  {
    name: 'custom_label_4',
    label: 'Custom Label 4',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Custom label for categorization',
  },
  {
    name: 'tax_category',
    label: 'Tax Category',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Product tax category',
    example: 'electronics',
  },
  {
    name: 'excluded_destination',
    label: 'Excluded Destination',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Excluded shipping destinations',
  },
  {
    name: 'included_destination',
    label: 'Included Destination',
    required: false,
    type: 'string',
    category: 'optional',
    description: 'Included shipping destinations',
  },
];

/**
 * Get required fields
 */
export const getRequiredFields = (): ACPFieldMetadata[] => {
  return ACP_FIELDS.filter((field) => field.required);
};

/**
 * Get recommended fields
 */
export const getRecommendedFields = (): ACPFieldMetadata[] => {
  return ACP_FIELDS.filter((field) => field.category === 'recommended');
};

/**
 * Get optional fields
 */
export const getOptionalFields = (): ACPFieldMetadata[] => {
  return ACP_FIELDS.filter((field) => field.category === 'optional');
};

/**
 * Get field by name
 */
export const getField = (name: string): ACPFieldMetadata | undefined => {
  return ACP_FIELDS.find((field) => field.name === name);
};

/**
 * Get all field names
 */
export const getAllFieldNames = (): string[] => {
  return ACP_FIELDS.map((field) => field.name);
};
